import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource';
import { data } from './data/resource';
import { gameHandler } from './functions/game-handler/resource';

/**
 * West of Haunted House Backend Definition
 * 
 * This defines the AWS Amplify Gen 2 backend infrastructure:
 * - Authentication (Cognito Identity Pool for guest access)
 * - Data (DynamoDB GameSessions table via Amplify Data)
 * - Lambda Function (Game handler for command processing)
 * - AppSync GraphQL API (processCommand custom query)
 * 
 * All resources are automatically tagged with:
 * - Project: west-of-haunted-house
 * - ManagedBy: vedfolnir
 * - Environment: dev/staging/prod (from AMPLIFY_ENV)
 * 
 * Requirements: 22.3, 22.4, 24.1, 24.2, 24.3, 11.1, 11.2
 * 
 * @see https://docs.amplify.aws/react/build-a-backend/
 */
const backend = defineBackend({
  auth,
  data,
  gameHandler,
});

/**
 * Apply required resource tags to all AWS resources
 * 
 * These tags enable:
 * - Cost tracking and allocation
 * - Resource discovery and management
 * - Automated cleanup scripts
 * - Compliance and governance
 * 
 * Requirements: 24.1, 24.2, 24.3, 24.4
 */
import { Stack, Tags } from 'aws-cdk-lib';

// Define required tags
const requiredTags = {
  'Project': 'west-of-haunted-house',
  'Owner': 'vedfolnir',
  'ManagedBy': 'vedfolnir', // Keep both for compatibility
  'Environment': process.env.AMPLIFY_ENV || 'dev'
};

// Apply tags to the Lambda function stack
const lambdaStack = Stack.of(backend.gameHandler.resources.lambda);
Object.entries(requiredTags).forEach(([key, value]) => {
  Tags.of(lambdaStack).add(key, value);
});

// Apply tags to the DynamoDB table stack
const tableStack = Stack.of(backend.data.resources.tables["GameSession"]);
Object.entries(requiredTags).forEach(([key, value]) => {
  Tags.of(tableStack).add(key, value);
});

// Apply tags to the GraphQL API stack
const apiStack = Stack.of(backend.data.resources.graphqlApi);
Object.entries(requiredTags).forEach(([key, value]) => {
  Tags.of(apiStack).add(key, value);
});

// Apply tags to the Auth stack (Identity Pool)
const authStack = Stack.of(backend.auth.resources.userPool);
Object.entries(requiredTags).forEach(([key, value]) => {
  Tags.of(authStack).add(key, value);
});

/**
 * Grant Lambda function access to DynamoDB table
 * 
 * This grants the game handler Lambda function read/write permissions
 * to the GameSessions DynamoDB table created by Amplify Data.
 * 
 * The table name is automatically generated by Amplify and passed via
 * environment variables to the Lambda function.
 * 
 * Requirements: 21.1, 21.2, 21.3, 21.4
 */
backend.data.resources.tables["GameSession"].grantReadWriteData(
  backend.gameHandler.resources.lambda
);

backend.gameHandler.addEnvironment(
  'GAME_SESSIONS_TABLE_NAME',
  backend.data.resources.tables["GameSession"].tableName
);
